r"""Inspect every dataset before we integrate it: fields, types, real samples, length stats.

This is the "inspect before integrating" deliverable. It loads each source, prints its schema and
a couple of raw examples, and reports character-length statistics over a sample. For MathPile
(gated) it works off a local download dir if present and reports per-``SubSet`` counts; otherwise
it says so and moves on.

Usage:
    python -m mathnano.data.inspect_data                          # public sources
    python -m mathnano.data.inspect_data --mathpile-dir data/raw/mathpile
    python -m mathnano.data.inspect_data --write mathnano/data/processed/data_statistics.md
"""
from __future__ import annotations

import argparse
import glob
import gzip
import io
import json
import os
import statistics as st
from contextlib import redirect_stdout
from typing import Optional

SAMPLE = 500  # docs to sample for length stats


def _stats(lengths: list[int]) -> str:
    if not lengths:
        return "(no data)"
    lengths.sort()
    p = lambda q: lengths[min(len(lengths) - 1, int(q * len(lengths)))]
    return (f"n={len(lengths)} chars: min={lengths[0]} p50={p(0.5)} "
            f"mean={int(st.mean(lengths))} p95={p(0.95)} max={lengths[-1]}")


def inspect_hf(name: str, loader) -> None:
    print(f"\n{'='*70}\n{name}\n{'='*70}")
    try:
        ds, sample_field = loader()
    except Exception as e:  # noqa: BLE001
        print(f"  SKIP ({type(e).__name__}): {repr(e)[:160]}")
        return
    feats = getattr(ds, "features", None)
    if feats:
        print("  features:", {k: str(v).split("(")[0] for k, v in feats.items()})
    lengths = []
    for i, ex in enumerate(ds):
        if i < 2:
            print(f"  --- example {i} ---")
            for k, v in ex.items():
                print(f"    {k}: {str(v).replace(chr(10), ' ')[:150]}")
        lengths.append(len(str(ex[sample_field])))
        if i + 1 >= SAMPLE:
            break
    print("  length stats on", sample_field, "->", _stats(lengths))


def inspect_mathpile(input_dir: str) -> None:
    print(f"\n{'='*70}\nGAIR/MathPile (local: {input_dir})\n{'='*70}")
    files = sorted(glob.glob(os.path.join(input_dir, "**", "*.jsonl.gz"), recursive=True))
    if not files:
        print("  SKIP: no *.jsonl.gz found (gated — download with huggingface-cli first).")
        return
    print(f"  files: {len(files)} (showing stats over first {SAMPLE} docs)")
    by_subset: dict[str, int] = {}
    lengths, shown = [], 0
    with gzip.open(files[0], "rt", encoding="utf-8") as f:
        for line in f:
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue
            sub = obj.get("subset", "?")
            by_subset[sub] = by_subset.get(sub, 0) + 1
            text = obj.get("text", "")
            lengths.append(len(text))
            if shown < 2:
                print(f"  --- {sub} sample ---\n    {text[:200].replace(chr(10), ' ')}")
                shown += 1
            if len(lengths) >= SAMPLE:
                break
    print("  per-SubSet (sampled):", by_subset)
    print("  length stats on text ->", _stats(lengths))


def run(mathpile_dir: Optional[str]) -> None:
    from datasets import load_dataset

    inspect_hf("openai/gsm8k (main/train)",
               lambda: (load_dataset("openai/gsm8k", "main", split="train"), "answer"))
    inspect_hf("nlile/hendrycks-MATH-benchmark (train)",
               lambda: (load_dataset("nlile/hendrycks-MATH-benchmark", split="train"), "solution"))
    inspect_hf("nvidia/OpenMathInstruct-2 (train, streamed)",
               lambda: (load_dataset("nvidia/OpenMathInstruct-2", split="train", streaming=True),
                        "generated_solution"))
    if mathpile_dir:
        inspect_mathpile(mathpile_dir)
    else:
        print("\n(MathPile not inspected — pass --mathpile-dir after downloading the gated set.)")


def main() -> None:
    ap = argparse.ArgumentParser(description="Inspect MathNano datasets")
    ap.add_argument("--mathpile-dir", type=str, default=None)
    ap.add_argument("--write", type=str, default=None, help="also write report to this markdown file")
    args = ap.parse_args()

    if args.write:
        buf = io.StringIO()
        with redirect_stdout(buf):
            run(args.mathpile_dir)
        text = buf.getvalue()
        print(text)
        os.makedirs(os.path.dirname(args.write), exist_ok=True)
        with open(args.write, "w") as f:
            f.write("# Data Statistics\n\nGenerated by `inspect_data.py`.\n\n```\n" + text + "\n```\n")
        print(f"\nWrote report to {args.write}")
    else:
        run(args.mathpile_dir)


if __name__ == "__main__":
    main()
